dist: xenial

matrix:
  include:
    - env:
        - PHP_VERSION=5.6
        - PARSER_VERSION=^1.0
    - env:
        - PHP_VERSION=5.6
        - PARSER_VERSION=^2.0
    - env:
        - PHP_VERSION=5.6
        - PARSER_VERSION=^3.0
    - env:
        - PHP_VERSION=7.0
        - PARSER_VERSION=^2.0
    - env:
        - PHP_VERSION=7.0
        - PARSER_VERSION=^3.0
    - env:
        - PHP_VERSION=7.1
        - PARSER_VERSION=^3.0
    - env:
        - PHP_VERSION=7.2
        - PARSER_VERSION=^3.0
    - env:
        - PHP_VERSION=7.3
        - PARSER_VERSION=^3.0

before_install:
  - travis_retry docker pull registry.gitlab.com/grahamcampbell/php:$PHP_VERSION
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION require "nikic/php-parser:${PARSER_VERSION}" --no-update -n

install:
  - travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint composer registry.gitlab.com/grahamcampbell/php:$PHP_VERSION install --no-suggest --prefer-dist -n -o

script:
  - docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint vendor/bin/phpunit registry.gitlab.com/grahamcampbell/php:$PHP_VERSION --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry docker run -it -w /data -v ${PWD}:/data:delegated --entrypoint ocular registry.gitlab.com/grahamcampbell/php:$PHP_VERSION code-coverage:upload --format=php-clover build/logs/clover.xml
